-- AlterTable
ALTER TABLE `mesin` MODIFY `kategori` ENUM('PROGRESIVE_TRANSFER', 'FINE_BLANKING', 'SECONDARY', 'PRESS', 'TACI') NOT NULL DEFAULT 'PRESS';

-- AlterTable
ALTER TABLE `user` MODIFY `role` ENUM('PRODUKSI', 'QUALITY', 'MAINTENANCE', 'DIE_MAINT', 'ENGINEERING', 'MARKETING', 'COMMERCIAL', 'PPIC', 'HCPGA', 'WRH_CIBITUNG', 'GA', 'WAREHOUSE', 'PURCHASING', 'HC', 'ACCOUNTING', 'FINANCE', 'SUPERVISOR', 'ADMIN') NOT NULL DEFAULT 'PRODUKSI';
