events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # Backend App
    upstream toshin_app {
        server app:4001;
    }

    server {
        listen 80;
        server_name localhost;

        # Frontend / API
        location / {
            proxy_pass http://toshin_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # WebSocket support
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        # phpMyAdmin
        location /phpmyadmin/ {
            proxy_pass http://toshin-phpmyadmin/;
            proxy_set_header Host $host;
        }

        # RedisInsight
        location /redisinsight/ {
            proxy_pass http://toshin-redis-insight:8001/;
            proxy_set_header Host $host;
        }
    }
}
