-- AlterTable
ALTER TABLE `user` MODIFY `role` ENUM('PRODUKSI', 'QUALITY', 'MAINTENANCE', 'DIE_MAINT', 'ENGINEERING', 'MARKETING', 'COMMERCIAL', 'PPIC', 'HCPGA', 'WRH_CIBITUNG', 'GA', 'WAREHOUSE', 'PURCHASING', 'HC', 'ACCOUNTING', 'FINANCE', 'SUPERVISOR', 'MANDOR', 'ADMIN', 'HR') NOT NULL DEFAULT 'PRODUKSI';
